import type { Metadata } from "next";
import "./globals.css";
import { listClasses } from "./lib/utils";

export const metadata: Metadata = {
  title: "Elijah Cirioli",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
