import type { Metadata } from "next";
// import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "./components/Footer";

config.autoAddCss = false;

export const metadata: Metadata = {
	title: "Elijah Cirioli",
	description: "Generated by create next app",
};

// TODO: replace
// const fontMontserratBetter = Montserrat({ subsets: ["latin"] });
const fontMontserrat = localFont({
	src: "../../public/fonts/Montserrat/Montserrat-VariableFont_wght.ttf",
	display: "swap",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={fontMontserrat.className}>
				{children}
				<Footer />
			</body>
		</html>
	);
}
