import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { listClasses } from "./lib/utils";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "./components/Footer";

config.autoAddCss = false;

export const metadata: Metadata = {
	title: "Elijah Cirioli",
	description: "Generated by create next app",
};

const fontMontserrat = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={fontMontserrat.className}>
				{children}
				<Footer />
			</body>
		</html>
	);
}
